info:
      description: aplicacion mock demo_log2

server:
      port: 7777

spring:
      application:
        name: demo_log2
eureka:
      client:
        serviceUrl:
            defaultZone:  http://localhost:5555/eureka
      instance:
        preferIpAddress: true